version: '3.4'
services:
  api_gateway:
    image: api_gateway
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://banco-apli:3308/projeto_api?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://banco-apli:3308/projeto_api?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin123
    ports:
      - 8100:8100
    networks:
      - net-networks
    depends_on:
      - banco-apli
      
  banco-apli:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
     TZ: America/Sao_paulo
     MYSQL_ROOT_PASSWORD: admin123
     MYSQL_USER: docker
     MYSQL_PASSWORD: admin123
     MYSQL_DATABASE: projeto_api
     MYSQL_ROOT_HOST: '%'
     MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - net-networks


networks:
  net-networks:
    driver: bridge