version: '3.4'

services:
  Api_Gateway:
    image: danilosn562/Api_Gateway:0.0.1-SNAPSHOT
    ports:
      - 8100:8100
    networks:
      - danilo-networks
      
  banco-apli:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
     TZ: America/Sao_paulo
     MYSQL_ROOT_PASSWORD: admin123
     MYSQL_USER: docker
     MYSQL_PASSWORD: admin123
     MYSQL_DATABASE: projeto_api
     MYSQL_ROOT_HOST: '%'
     MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - danilo-networks    
      
networks:
  danilo-networks:
    driver: bridge